### ISSUE TITLE
Save page Offline

### ISSUE THREAD

**Issue by Gunkev** [mozilla-mobile/outreachy-UX-2020#31]
### What is the problem you are trying to solve?
Saving page offline
### Why is it a problem?
This is problem cause it may happens that user do not have a good connection, having low batteries, or simply will like to stay offline in order to enjoy their lectures and be safe from ads. It will quite enhance user experience to access some of those informations eventhough offline.
### How would you solve the problem? What is your design proposal?
An idea is to propose user to save the current page in which they are found offline in order to access it later on when facing some issues due to connection. Doing that I will propose lso to permit user to view list of save page and eventually delete the ones that are no more needed. Below is a sketch that shows more details.

![save page](https://user-images.githubusercontent.com/36812576/77103994-8ec29700-6a1b-11ea-8db7-c07dfff47acf.png)

![view save page](https://user-images.githubusercontent.com/36812576/77104011-984bff00-6a1b-11ea-88f7-4229d9fcf01a.png)

### How would you measure your designs effectiveness?
One of my preferred method is to work directly with group of users taking good notes of user feedback and working thoroughly with a group of experienced team in order to get more ideas and proposals.

**Comment by topotropic** [comment]
Thanks for your proposal! 

In your design, the icons in the bottom bar look too close together. We try to have big enough touch targets so that users don't accidentally tap on the wrong icon. Could you think of another way to save a page for offline reading? 

The saved pages could also show up in the Firefox Preview Library, it's accessible via the menu so we would not need a dedicated menu entry here. 

Otherwise looking good! Thanks!

**Comment by Gunkev** [comment]
@topotropic  her is an update. Comment are welcome
![save-page-update](https://user-images.githubusercontent.com/36812576/78357101-bdf30f80-75a8-11ea-9634-1231bab6851a.png)
