### ISSUE TITLE
Force web content to use dark mode

### ISSUE THREAD

**Issue by areeshatariq** [mozilla-mobile/outreachy-UX-2020#54]
### What is the problem you are trying to solve?
[#2139](https://github.com/mozilla-mobile/fenix/issues/2139) Force web content to use dark mode
### Why is it a problem?
Currently, when the user enables the dark mode in Fenix, it converts the user interface of the application into dark mode but the dark mode is not enabled for the web pages. The theme of the websites is not affected by dark mode. This fails the point of using dark mode if suddenly a web-page goes full bright into the eyes.
### How would you solve the problem? What is your design proposal

- Users will have the option to enable dark mode for websites when the dark theme is enabled.
- If the user selects Follow device theme option, then the dark mode for websites option will appear only if the device theme is dark.

### Design
By default, the Dark mode for websites option will be checked (enabled).

<p align="center"><img src="https://user-images.githubusercontent.com/24654457/77798813-68dd6800-7095-11ea-9fcb-0f1289743ad2.jpg" width="50%" height="50%"></p>

The user has the option to uncheck the Dark mode for websites option while the dark theme is enabled.

<p align="center"><img src="https://user-images.githubusercontent.com/24654457/77798837-74309380-7095-11ea-884a-ca873135e49c.jpg" width="50%" height="50%"></p>

If the dark theme is disabled, the dark mode for websites option will be greyed out.

<p align="center"><img src="https://user-images.githubusercontent.com/24654457/77800706-36356e80-7099-11ea-849b-590df6d53c68.jpg" width="50%" height="50%"></p>

### How would you measure your designs effectiveness?
The above design will be effective if:
- The feature is implemented in a way that the user is able to interact with the sites in the same way as in the light theme, it would be effective. 
- The user does not see a flash of white/light colors before the dark theme is applied.
- Websites do not take longer than usual to load.

**Comment by topotropic** [comment]
Thanks for the proposal, looking good!

**Comment by garrett** [comment]
Is it possible to have Firefox switch between light and dark mode, possibly based on time or ambient light in the room? (The latter is possibly a battery drain, if Firefox has to check for that periodically. At least one could set a general bedtime and waking time.)

My phone (OnePlus 6T) has settings to make the system light and dark, but it doesn't auto-switch. I leave it in dark, because I don't want to dive into the settings every evening and morning to switch it. So relying on a system theme won't help me (and others with phones that don't auto-switch) at all.

I don't want pages inverted (even with a hue shift) just because I prefer the darker UI for Firefox or for my phone. But I do actually want dark mode when I'm looking at pages at nighttime, starting a little while before I'm getting ready to sleep.

_So, in other words_: Thanks for working on this feature! I'm looking forward to it a _lot_. However, as it is currently designed, it wouldn't work well for me. (And I bet I'm not the only one.) Could it also be automatically activated/deactivated by time?

**Comment by areeshatariq** [comment]
@garrett Firefox Preview currently does not have auto-switch feature on the time basis. But it would be a great idea to introduce this feature. The user could have the option of enabling the auto-switch feature. The application would set a general bedtime that could be customized by the user according to the needs. @topotropic what do you say?
