### ISSUE TITLE
Having two "save to collection" options.

### ISSUE THREAD

**Issue by Vaishnavi-Reddy-Kancharla** [mozilla-mobile/outreachy-UX-2020#85]
**What is the problem you are trying to solve?**
Having two "save to collection" options.
**Why is it a problem?**
It is not necessary to have two options of “save to collections” near open tabs.
**How would you solve the problem? What is your design proposal?**
We can remove the “save to collections” option from the kebab menu because there is already an option “save to collections” below open tabs.

![91970621_1036701680063822_2682625998872117248_n](https://user-images.githubusercontent.com/60965381/78126568-56b24f80-7430-11ea-96dd-5f18fd738833.jpg)
![91687998_2309551449350221_8583434975041290240_n](https://user-images.githubusercontent.com/60965381/78126733-97aa6400-7430-11ea-9098-50674a06f40b.jpg)

**How would you measure your designs effectiveness?**
It's better to have a web page not cluttered and not have two options with the same functionality.

**Comment by Gunkev** [comment]
@vaishnavi4444 thanks I understand your thought but this is when user have a few number of open tabs like 3 or less. I think having those two is important in this context since it facilitate accessibility. In the case of having a long list of open tabs in his home page it become necessary. if the user is at the beginning of the list he can use the kebab menu to add some oen tabs useful to him in his collection and if the user is at the end or near he will just tap the "add to collection button" below rather than scrolling up and down each time.
But another solution that come to my mine if you want just one way to save collections instead of two is that you can propose to have the "open tab with the kebab menu" fix at the top of the screen on scrolling such that it remains visible as we scroll up and down.

**Comment by Vaishnavi-Reddy-Kancharla** [comment]
@Gunkev oh I got it now. Yes, I think what you said is right! I think fixing the "open tab with kebab menu" on the top of the screen would make us eliminate having two "save to collections" options. Thanks for your insight and also what to do think about having to options for "save to collections"

**Comment by Gunkev** [comment]
As I explain above having two options for "save to collection" is also good as presently in the app it facilitate accessibility
